export const SLASH_STEP_TWO = 500
export const SLASH_STEP_THREE = 1500

export const HOME_APPEARING_DURATION = 1000
export const HOME_APPEARING_DELAY = 3000

export const INTRO_TEXT_DELAY = 4000
export const INTRO_NEXT_BTN_DELAY = 7000

export const ABOUT_IN_DURATION = 500
export const ABOUT_OUT_DURATION = 250

export const TODAY_QUOTE_WITH_INTRO = 250
export const TODAY_QUOTE_WITHOUT_INTRO = 4000


